'use client';
import { ChevronLeft, ChevronRight, Dices } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { balanceQuestions, Category } from '@/data/balanceQuestions';
import { ShareButton } from './AppShell';

const cats: (Category | '전체')[] = ['전체', '일상', '음식', '연애', '친구', '회사', '황당한 질문'];
export default function BalanceGame() {
  const [cat, setCat] = useState<Category | '전체'>('전체'); const [index, setIndex] = useState(0); const [selected, setSelected] = useState<'left' | 'right' | null>(null);
  const list = useMemo(() => cat === '전체' ? balanceQuestions : balanceQuestions.filter(q => q.category === cat), [cat]); const q = list[index % list.length];
  useEffect(() => { setIndex(Math.floor(Math.random() * list.length)); }, [list]);
  const random = () => { let next = Math.floor(Math.random() * list.length); if (list.length > 1 && next === index % list.length) next = (next + 1) % list.length; setIndex(next); setSelected(null); };
  return <main className="mx-auto max-w-4xl px-4 pb-16 pt-8 sm:px-6 sm:pt-12"><div className="mb-7 flex items-end justify-between"><div><span className="text-sm font-black text-coral">BALANCE GAME</span><h1 className="mt-1 text-2xl font-black sm:text-3xl">하나를 고르고, 이유를 말해봐요</h1></div><span className="text-sm font-bold text-[#958d82]">랜덤 · {list.length}개 질문</span></div><div className="mb-7 flex gap-2 overflow-x-auto pb-2">{cats.map(c => <button key={c} onClick={() => { setCat(c); setIndex(0); setSelected(null); }} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-extrabold transition ${cat === c ? 'bg-ink text-white' : 'bg-white text-[#747b83] hover:bg-[#f3eee7]'}`}>{c}</button>)}</div><div key={`${cat}-${index}`} className="card-enter rounded-[32px] bg-white p-5 shadow-soft sm:p-10"><div className="grid gap-3 sm:grid-cols-[1fr_auto_1fr] sm:items-stretch"><button onClick={() => setSelected('left')} className={`min-h-32 rounded-3xl border-4 p-5 text-xl font-black transition sm:min-h-48 sm:text-2xl ${selected === 'left' ? 'border-coral bg-[#fff0eb] text-coral' : 'border-[#f1ebe2] hover:border-[#ffc2b8]'}`}>{q.left}{selected === 'left' && <span className="mt-3 block text-sm">✓ 이쪽!</span>}</button><div className="grid place-items-center text-sm font-black text-[#b6ada1]">VS</div><button onClick={() => setSelected('right')} className={`min-h-32 rounded-3xl border-4 p-5 text-xl font-black transition sm:min-h-48 sm:text-2xl ${selected === 'right' ? 'border-purple bg-[#f2efff] text-purple' : 'border-[#f1ebe2] hover:border-[#c9c0ff]'}`}>{q.right}{selected === 'right' && <span className="mt-3 block text-sm">✓ 이쪽!</span>}</button></div><div className="mt-7 flex flex-wrap items-center justify-center gap-2 border-t border-[#f1ebe2] pt-6"><button onClick={random} className="rounded-2xl border-2 border-[#ebe4da] bg-white px-4 py-3 text-sm font-extrabold"><ChevronLeft size={16} className="mr-1 inline"/> 이전</button><button onClick={random} className="rounded-2xl bg-ink px-5 py-3 text-sm font-extrabold text-white">다음 질문 <ChevronRight size={16} className="ml-1 inline"/></button><button onClick={random} className="rounded-2xl border-2 border-[#ebe4da] bg-white px-4 py-3 text-sm font-extrabold"><Dices size={16} className="mr-1 inline"/> 랜덤</button><ShareButton text={`${q.left} VS ${q.right}`} /></div></div></main>;
}
