'use client';
import { Dices, Eye, RotateCcw } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { choseongQuestions, ChoseongCategory } from '@/data/choseongQuestions';

const categories: ChoseongCategory[] = ['2글자', '3글자', '4글자'];
export default function ChoseongGame() {
  const [category, setCategory] = useState<ChoseongCategory>('2글자'); const [index, setIndex] = useState(0); const [revealed, setRevealed] = useState(false);
  const list = useMemo(() => choseongQuestions.filter(q => q.category === category), [category]); const question = list[index % list.length];
  useEffect(() => { setIndex(Math.floor(Math.random() * list.length)); }, [list]);
  const draw = () => { let next = Math.floor(Math.random() * list.length); if (list.length > 1 && next === index % list.length) next = (next + 1) % list.length; setIndex(next); setRevealed(false); };
  return <main className="mx-auto max-w-3xl px-4 pb-16 pt-8 sm:px-6 sm:pt-12"><div className="mb-7 flex items-end justify-between"><div><span className="text-sm font-black text-[#cc8b18]">CHOSEONG QUIZ</span><h1 className="mt-1 text-2xl font-black sm:text-3xl">초성만 보고 맞혀보세요!</h1></div><span className="text-sm font-bold text-[#958d82]">랜덤 · {list.length}개 문제</span></div><div className="mb-8 flex gap-2">{categories.map(item => <button key={item} onClick={() => { setCategory(item); setIndex(0); setRevealed(false); }} className={`flex-1 rounded-full px-4 py-3 text-sm font-extrabold transition ${category === item ? 'bg-ink text-white' : 'bg-white text-[#747b83] hover:bg-[#f3eee7]'}`}>{item}</button>)}</div><div key={`${category}-${index}`} className="card-enter rounded-[32px] bg-white p-7 text-center shadow-soft sm:p-12"><span className="rounded-full bg-[#fff4cf] px-3 py-1 text-xs font-black text-[#b77a13]">{question.category} 문제</span><div className="mt-10 text-6xl font-black tracking-[.25em] text-[#d99522] sm:text-8xl">{question.hint}</div><div className="mt-9 min-h-14">{revealed ? <p className="text-3xl font-black text-ink">정답은 <span className="text-[#d99522]">{question.answer}</span>!</p> : <p className="font-bold text-[#9b9388]">친구들과 10초 동안 생각해보세요</p>}</div><button onClick={() => setRevealed(!revealed)} className="mt-6 min-h-14 rounded-2xl bg-[#d99522] px-7 font-black text-white shadow-lg transition hover:scale-105 active:scale-95"><Eye size={19} className="mr-2 inline"/>{revealed ? '정답 숨기기' : '정답 보기'}</button></div><div className="mt-6 flex justify-center gap-2"><button onClick={draw} className="rounded-2xl border-2 border-[#ebe4da] bg-white px-5 py-3 text-sm font-extrabold"><Dices size={16} className="mr-1 inline"/> 랜덤 문제</button><button onClick={() => { setIndex(0); setRevealed(false); }} aria-label="초성게임 다시 시작" className="rounded-2xl border-2 border-[#ebe4da] bg-white px-4 py-3 text-sm font-extrabold"><RotateCcw size={16}/></button></div></main>;
}
